# Generated by Django 5.2.7 on 2025-10-06 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsector', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('variedad_tipo', models.CharField(max_length=100)),
                ('calidad', models.CharField(max_length=50)),
                ('unidad_comercializacion', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_region', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.region')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_minimo', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_maximo', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_promedio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.mercado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.producto')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.region')),
            ],
            options={
                'verbose_name_plural': 'Datos de precios',
                'indexes': [models.Index(fields=['fecha'], name='datos_preci_fecha_5cda50_idx'), models.Index(fields=['region', 'producto'], name='datos_preci_region__3ae231_idx')],
            },
        ),
    ]
