# -*- coding: utf-8 -*-
"""actualizacion_datos_semanal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTGKHi4IE88L56rxWe8qYX7KsUnC6xs-
"""

import requests
import pandas as pd
import numpy as np
import joblib
import re
import os
from datetime import datetime, date
import schedule
import time

# ==========================================
# CONFIGURACIÓN GENERAL
# ==========================================

RESOURCE_ID = "cb9e0b61-48cd-4d61-a636-c67d9150eeba"
API_URL = "https://datos.odepa.gob.cl/api/3/action/datastore_search"
LIMITE_REGISTROS = 300000

# Carpetas locales
BASE_DIR = "/content/drive/MyDrive/Semestre 2025-2/CAPSTONE/agrochile/modelo IA"
MODELOS_DIR = os.path.join(BASE_DIR, "retrained_top_10_models_2025")
SALIDA_DIR = os.path.join(BASE_DIR, "salidas_semanales")

os.makedirs(SALIDA_DIR, exist_ok=True)

# Lista de combinaciones de producto/región a predecir
COMBINACIONES = [
    ("Limón (por_kilo)", "Región del Maule"),
    ("Limón (por_kilo)", "Región de Los Lagos"),
    ("Limón (por_kilo)", "Región de Valparaíso"),
    ("Limón (por_kilo)", "Región de Ñuble"),
    ("Limón (por_kilo)", "Región del Biobío"),
    ("Naranja (por_kilo)", "Región de Coquimbo"),
    ("Zapallo (por_kilo)", "Región de Coquimbo"),
    ("Papa (por_kilo)", "Región de Valparaíso"),
    ("Mango (por_kilo)", "Región de Coquimbo"),
    ("Papa (por_kilo)", "Región de Coquimbo")
]

# ==========================================
# FUNCIONES PRINCIPALES
# ==========================================

def obtener_datos_odepa(limite=LIMITE_REGISTROS):
    """Descarga los datos actualizados de la API ODEPA"""
    print("📥 Descargando datos desde ODEPA...")
    params = {"resource_id": RESOURCE_ID, "limit": limite}
    r = requests.get(API_URL, params=params)
    r.raise_for_status()
    data = r.json()
    if not data.get("success", False):
        raise Exception("Error al obtener datos desde ODEPA")
    df = pd.DataFrame(data["result"]["records"])
    print(f"✅ Datos descargados: {len(df)} registros.")
    return df


def parse_number(s):
    if s is None:
        return None
    s = str(s).replace(',', '.')
    try:
        return float(s)
    except:
        return None


def infer_factor(unidad_text, categoria):
    if pd.isna(unidad_text):
        return None
    s = unidad_text.lower().strip()
    s = s.replace('$', '').replace('\u00A0', ' ').strip()

    # kilos explícitos
    m = re.search(r'(\d+[.,]?\d*)\s*\(?\s*kilo?s?\)?', s)
    if m:
        return parse_number(m.group(1))

    # unidades explícitas
    m_unid = re.search(r'(\d+)\s*(unidades|unidad|uds|u\b)', s)
    if m_unid:
        return int(m_unid.group(1))

    # docenas
    if 'media docena' in s or '½ docena' in s:
        return 6
    if 'docena' in s:
        return 12

    # cien unidades
    if 'cien unidades' in s or '100 unidades' in s:
        return 100

    # gramos o canastillos
    m_g = re.search(r'(\d+[.,]?\d*)\s*(gramos|gr\b)', s)
    if m_g:
        g = parse_number(m_g.group(1))
        return g / 1000 if g else None

    # rangos
    m_range = re.search(r'(\d+[.,]?\d*)\s*(?:a|-)\s*(\d+[.,]?\d*)', s)
    if m_range:
        a, b = parse_number(m_range.group(1)), parse_number(m_range.group(2))
        return (a + b) / 2 if a and b else None

    # fallback
    if categoria in ['por_kilo', 'por_caja', 'por_saco', 'por_bandeja', 'por_saco_malla']:
        return 1
    if categoria in ['por_unidad', 'por_atado', 'por_paquete']:
        return 1

    return None


def preprocesar_datos(df):
    """Normaliza y limpia los datos para predicción"""
    print("🔧 Preprocesando datos...")

    # Normalizar nombres
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

    # Conversión de precios
    for col in ['precio_minimo', 'precio_maximo', 'precio_promedio']:
        if col in df.columns:
            df[col] = (
                df[col]
                .astype(str)
                .str.replace('.', '', regex=False)
                .str.replace(',', '.', regex=False)
                .str.replace('$', '', regex=False)
            )
            df[col] = pd.to_numeric(df[col], errors='coerce')

    # Fecha
    df['fecha'] = pd.to_datetime(df['fecha'], errors='coerce')

    # Categoría unidad
    df['categoria_unidad'] = df['unidad_de_comercializacion'].apply(lambda x: (
        'por_kilo' if 'kilo' in str(x).lower() else
        'por_unidad' if 'unidad' in str(x).lower() else
        'por_atado' if 'atado' in str(x).lower() else
        'por_saco' if 'saco' in str(x).lower() else
        'por_bandeja' if 'bandeja' in str(x).lower() else
        'por_caja' if 'caja' in str(x).lower() else
        'por_malla' if 'malla' in str(x).lower() else
        'otros'
    ))

    df['factor_inferido'] = df.apply(
        lambda r: infer_factor(r['unidad_de_comercializacion'], r['categoria_unidad']),
        axis=1
    )

    df = df[df['factor_inferido'].notna()]
    df['precio_normalizado'] = df['precio_promedio'] / df['factor_inferido']
    df['producto_unidad'] = df['producto'] + ' (' + df['categoria_unidad'] + ')'

    print(f"✅ Datos preprocesados: {len(df)} registros.")
    return df


def crear_features(grupo):
    grupo = grupo.sort_values('fecha')
    grupo['mes'] = grupo['fecha'].dt.month
    grupo['ano'] = grupo['fecha'].dt.year
    grupo['dia_semana'] = grupo['fecha'].dt.weekday
    grupo['es_fin_de_semana'] = (grupo['dia_semana'] >= 5).astype(int)
    grupo['lag_1'] = grupo['precio_normalizado'].shift(1)
    grupo['lag_7'] = grupo['precio_normalizado'].shift(7)
    grupo['lag_30'] = grupo['precio_normalizado'].shift(30)
    grupo['rol_mean_7'] = grupo['precio_normalizado'].rolling(7).mean()
    grupo['rol_std_30'] = grupo['precio_normalizado'].rolling(30).std()
    grupo['pct_change_7'] = grupo['precio_normalizado'].pct_change(7)
    return grupo.dropna()


def predecir_producto_region(df, producto_unidad, region):
    modelo_path = os.path.join(
        MODELOS_DIR,
        f"{producto_unidad.replace(' ', '_').replace('(', '').replace(')', '')}_{region.replace(' ', '_')}_retrained.joblib"
    )

    if not os.path.exists(modelo_path):
        print(f"⚠️ Modelo no encontrado para {producto_unidad} - {region}")
        return None

    modelo = joblib.load(modelo_path)
    df_filt = df[(df['producto_unidad'] == producto_unidad) & (df['region'] == region)]
    if df_filt.empty:
        print(f"⚠️ No hay datos para {producto_unidad} - {region}")
        return None

    df_feat = df_filt.groupby(['producto', 'region'], group_keys=False).apply(crear_features)
    features = ['mes', 'ano', 'dia_semana', 'es_fin_de_semana', 'lag_1', 'lag_7', 'lag_30', 'rol_mean_7', 'rol_std_30', 'pct_change_7']
    X = df_feat[features]
    df_feat['prediccion'] = modelo.predict(X)
    return df_feat[['fecha', 'producto_unidad', 'region', 'precio_normalizado', 'prediccion']]


def actualizar_predicciones():
    """Pipeline completo semanal"""
    print(f"\n🚀 Ejecutando actualización semanal - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    df_raw = obtener_datos_odepa()
    df_clean = preprocesar_datos(df_raw)

    resultados = []
    for prod, reg in COMBINACIONES:
        pred = predecir_producto_region(df_clean, prod, reg)
        if pred is not None:
            resultados.append(pred)

    if resultados:
        df_final = pd.concat(resultados)
        salida_path = os.path.join(SALIDA_DIR, f"predicciones_semana_{date.today()}.csv")
        df_final.to_csv(salida_path, index=False)
        print(f"✅ Predicciones guardadas en {salida_path}")
    else:
        print("⚠️ No se generaron predicciones.")


# ==========================================
# PROGRAMACIÓN AUTOMÁTICA
# ==========================================

def programar_tarea():
    """Programa la tarea cada lunes a las 15:00"""
    schedule.every().monday.at("15:00").do(actualizar_predicciones)
    print("🕒 Tarea programada: cada lunes a las 15:00.")
    while True:
        schedule.run_pending()
        time.sleep(60)


if __name__ == "__main__":
    programar_tarea()