# -*- coding: utf-8 -*-
"""prediccion_flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1weP_NtB-a1KQC_5XgYMYGxpptBfEznpQ
"""

from flask import Flask, request, jsonify
import pandas as pd
import joblib
import numpy as np
import os
from datetime import timedelta, date

app = Flask(__name__)

# ==============================
# CONFIGURACIÓN
# ==============================
MODELOS_DIR = "/content/drive/MyDrive/Semestre 2025-2/CAPSTONE/agrochile/modelo IA/retrained_top_10_models_2025"
DATOS_RECIENTES = "salidas/predicciones_api_2025-11-10.csv"

# ==============================
# FUNCIÓN PRINCIPAL DE PREDICCIÓN
# ==============================
def predecir_futuro(producto, unidad, region, horizonte_dias):
    producto_unidad = f"{producto} ({unidad})"
    cleaned_producto = producto_unidad.replace(" ", "_").replace("/", "_").replace("(", "").replace(")", "")
    cleaned_region = region.replace(" ", "_").replace("/", "_")
    modelo_path = os.path.join(MODELOS_DIR, f"{cleaned_producto}_{cleaned_region}_retrained.joblib")

    if not os.path.exists(modelo_path):
        return {"error": f"No se encontró modelo para {producto_unidad} - {region}"}

    modelo = joblib.load(modelo_path)

    df = pd.read_csv(DATOS_RECIENTES, parse_dates=["fecha"])
    df_filt = df[(df['producto_unidad'] == producto_unidad) & (df['region'] == region)].copy()

    if df_filt.empty:
        return {"error": f"No hay datos recientes para {producto_unidad} - {region}"}

    ultima_fila = df_filt.sort_values("fecha").iloc[-1].copy()
    pred_hist = list(df_filt['precio_normalizado'].tail(30).values)
    predicciones = []

    for _ in range(horizonte_dias):
        nueva_fecha = ultima_fila["fecha"] + timedelta(days=1)

        pred_hist.append(ultima_fila["precio_normalizado"])
        if len(pred_hist) > 30:
            pred_hist.pop(0)

        nueva_fila = ultima_fila.copy()
        nueva_fila["fecha"] = nueva_fecha
        nueva_fila["mes"] = nueva_fecha.month
        nueva_fila["ano"] = nueva_fecha.year
        nueva_fila["dia_semana"] = nueva_fecha.weekday()
        nueva_fila["es_fin_de_semana"] = int(nueva_fila["dia_semana"] >= 5)

        nueva_fila["lag_1"] = pred_hist[-1]
        nueva_fila["lag_7"] = pred_hist[-7] if len(pred_hist) >= 7 else pred_hist[-1]
        nueva_fila["lag_30"] = pred_hist[0]
        nueva_fila["rol_mean_7"] = np.mean(pred_hist[-7:]) if len(pred_hist) >= 7 else np.mean(pred_hist)
        nueva_fila["rol_std_30"] = np.std(pred_hist)
        nueva_fila["pct_change_7"] = (pred_hist[-1] - pred_hist[-7]) / pred_hist[-7] if len(pred_hist) >= 7 else 0

        X = nueva_fila[["mes", "ano", "dia_semana", "es_fin_de_semana",
                        "lag_1", "lag_7", "lag_30", "rol_mean_7", "rol_std_30", "pct_change_7"]].values.reshape(1, -1)

        pred = modelo.predict(X)[0]
        nueva_fila["prediccion"] = pred
        predicciones.append({
            "fecha": nueva_fecha.strftime("%Y-%m-%d"),
            "producto_unidad": producto_unidad,
            "region": region,
            "prediccion": float(pred)
        })
        ultima_fila["precio_normalizado"] = pred

    return {"predicciones": predicciones}

# ==============================
# ENDPOINT API
# ==============================
@app.route("/predecir", methods=["GET"])
def predecir_endpoint():
    producto = request.args.get("producto")
    unidad = request.args.get("unidad")
    region = request.args.get("region")
    horizonte = int(request.args.get("horizonte", 7))

    if not all([producto, unidad, region]):
        return jsonify({"error": "Debe especificar producto, unidad y región"}), 400

    resultado = predecir_futuro(producto, unidad, region, horizonte)
    return jsonify(resultado)

# ==============================
# EJECUTAR
# ==============================
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)