# -*- coding: utf-8 -*-
"""preprocesamiento_odepa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reDhrJRu8x2Eq_st6UHDnH77838t5z2O
"""

import re
import pandas as pd
import numpy as np

# =========================
# BLOQUE 1: Limpieza básica
# =========================
def limpiar_precios(df):
    for col in ['precio_minimo', 'precio_maximo', 'precio_promedio']:
        df[col] = (
            df[col]
            .astype(str)
            .str.replace('.', '', regex=False)      # quita separadores de miles
            .str.replace(',', '.', regex=False)     # cambia coma por punto decimal
            .str.replace('$', '', regex=False)      # quita símbolo de pesos
            .astype(float)
        )
    return df


# ================================
# BLOQUE 2: Categorización e inferencia
# ================================
def parse_number(s):
    if s is None:
        return None
    s = s.replace(',', '.')
    try:
        return float(s)
    except:
        return None


def infer_factor(unidad_text, categoria):
    if pd.isna(unidad_text):
        return None
    s = unidad_text.lower().strip()
    s = s.replace('$', '').replace('\u00A0', ' ').strip()

    # --- Kilos explícitos ---
    m = re.search(r'(\d+[.,]?\d*)\s*\(?\s*kilo?s?\)?', s)
    if m:
        return parse_number(m.group(1))

    # --- Unidades explícitas ---
    m_unid = re.search(r'(\d+)\s*(unidades|unidad|uds|u\b)', s)
    if m_unid:
        return int(m_unid.group(1))

    # --- Docenas ---
    if 'media docena' in s or '½ docena' in s:
        return 6
    if 'docena' in s:
        return 12

    # --- Cien unidades ---
    if 'cien unidades' in s or '100 unidades' in s:
        return 100

    # --- Gramos o canastillos ---
    m_g = re.search(r'(\d+[.,]?\d*)\s*(gramos|gr\b)', s)
    if m_g:
        g = parse_number(m_g.group(1))
        return g / 1000 if g else None

    # --- Rangos (ej: "0,5 a 1 kilo") ---
    m_range = re.search(r'(\d+[.,]?\d*)\s*(?:a|-)\s*(\d+[.,]?\d*)', s)
    if m_range:
        a, b = parse_number(m_range.group(1)), parse_number(m_range.group(2))
        return (a + b) / 2 if a and b else None

    # --- Fallbacks por categoría ---
    if categoria in ['por_kilo', 'por_caja', 'por_saco', 'por_bandeja', 'por_malla']:
        return 1
    if categoria in ['por_unidad', 'por_atado', 'por_paquete']:
        return 1

    return None


def categorizar_unidades(df):
    df['categoria_unidad'] = df['unidad_de_comercializacion'].apply(lambda x: (
        'por_kilo' if 'kilo' in str(x).lower() else
        'por_unidad' if 'unidad' in str(x).lower() else
        'por_atado' if 'atado' in str(x).lower() else
        'por_saco' if 'saco' in str(x).lower() else
        'por_bandeja' if 'bandeja' in str(x).lower() else
        'por_caja' if 'caja' in str(x).lower() else
        'por_malla' if 'malla' in str(x).lower() else
        'otros'
    ))

    df['factor_inferido'] = df.apply(
        lambda r: infer_factor(r['unidad_de_comercializacion'], r['categoria_unidad']),
        axis=1
    )

    # eliminar ambigüedades o sin factor
    df = df[df['factor_inferido'].notna()]
    return df


# =====================================
# BLOQUE 3: Precio normalizado por unidad
# =====================================
def normalizar_precios(df):
    df['precio_normalizado'] = df['precio_promedio'] / df['factor_inferido']
    df['producto_unidad'] = df['producto'] + ' (' + df['categoria_unidad'] + ')'
    return df


# =====================================
# BLOQUE 4: Creación de features temporales
# =====================================
def crear_features(df):
    df['fecha'] = pd.to_datetime(df['fecha'], errors='coerce')
    df = df.sort_values(['producto', 'region', 'fecha']).copy()

    # variables de tiempo
    df['mes'] = df['fecha'].dt.month
    df['ano'] = df['fecha'].dt.year
    df['dia_semana'] = df['fecha'].dt.weekday
    df['es_fin_de_semana'] = (df['dia_semana'] >= 5).astype(int)

    # lags, rolling y variaciones
    def agregar_features(grupo):
        grupo = grupo.sort_values('fecha')
        grupo['lag_1'] = grupo['precio_normalizado'].shift(1)
        grupo['lag_7'] = grupo['precio_normalizado'].shift(7)
        grupo['lag_30'] = grupo['precio_normalizado'].shift(30)
        grupo['rol_mean_7'] = grupo['precio_normalizado'].rolling(7).mean()
        grupo['rol_std_30'] = grupo['precio_normalizado'].rolling(30).std()
        grupo['pct_change_7'] = grupo['precio_normalizado'].pct_change(7)
        return grupo

    df = df.groupby(['producto', 'region'], group_keys=False).apply(agregar_features)
    df = df.dropna().reset_index(drop=True)
    return df


# =====================================
# FUNCIÓN MAESTRA
# =====================================
def preprocesar_odepa(df):
    df = limpiar_precios(df)
    df = categorizar_unidades(df)
    df = normalizar_precios(df)
    df = crear_features(df)
    return df


# =====================================
# USO DIRECTO DEL SCRIPT
# =====================================
if __name__ == "__main__":
    input_path = "data/odepa_raw.csv"
    output_path = "data/odepa_features.csv"

    print("Cargando datos...")
    df_raw = pd.read_csv(input_path, encoding='utf-8')

    print("Procesando dataset completo...")
    df_features = preprocesar_odepa(df_raw)

    print(f"Proceso finalizado. Registros: {len(df_features)}")
    df_features.to_csv(output_path, index=False)
    print(f"Dataset listo para modelos guardado en: {output_path}")