# -*- coding: utf-8 -*-
"""prediccion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xDiYGWphIx5pH91xcJY87eNRRwGu9N2n
"""

import pandas as pd
import joblib
import numpy as np
import os
from datetime import timedelta, date
import argparse

# ==============================
# CONFIGURACIÓN
# ==============================

MODELOS_DIR = "/content/drive/MyDrive/Semestre 2025-2/CAPSTONE/agrochile/modelo IA/retrained_top_10_models_2025" #CAMBIAR
DATOS_RECIENTES = "salidas/predicciones_api_2025-11-10.csv"  # tu último CSV generado (CAMBIAR)
SALIDA_DIR = "salidas_predicciones"
os.makedirs(SALIDA_DIR, exist_ok=True)

# ==============================
# PARÁMETROS DE ENTRADA
# ==============================

def parse_arguments():
    parser = argparse.ArgumentParser(description="Realiza predicciones de precios de productos agrícolas.")
    parser.add_argument("--producto", required=True, help="Ingrese el producto (ej: Limón, Papa, Naranja, Zapallo, Mango)")
    parser.add_argument("--unidad", required=True, help="Ingrese la unidad (por_kilo, por_unidad, etc.)")
    parser.add_argument("--region", required=True, help="Ingrese la región (ej: Región de Coquimbo)")
    parser.add_argument("--horizonte", type=int, choices=[7, 4, 8], required=True,
                        help="Seleccione horizonte temporal: 7 (7 días), 4 (4 semanas), 8 (2 meses)")

    args = parser.parse_args()

    if args.horizonte == 7:
        unidad_tiempo = "día"
    else:
        unidad_tiempo = "semana"

    return args.producto, args.unidad, args.region, args.horizonte, unidad_tiempo

# ==============================
# FUNCIÓN DE PREDICCIÓN
# ==============================

def predecir_futuro(df, producto, unidad, region, horizonte, unidad_tiempo):
    producto_unidad = f"{producto} ({unidad})"
    # Clean up the model path to remove potentially problematic characters
    cleaned_producto_unidad = producto_unidad.replace(" ", "_").replace("/", "_").replace("(", "").replace(")", "")
    cleaned_region = region.replace(" ", "_").replace("/", "_")
    modelo_path = os.path.join(MODELOS_DIR, f"{cleaned_producto_unidad}_{cleaned_region}_retrained.joblib")


    if not os.path.exists(modelo_path):
        print(f"No se encontró modelo para {producto_unidad} - {region}")
        return None

    modelo = joblib.load(modelo_path)

    df_filt = df[(df['producto_unidad'] == producto_unidad) & (df['region'] == region)].copy()
    if df_filt.empty:
        print(f"No hay datos recientes para {producto_unidad} - {region}")
        return None

    # Tomar la última fila (último día observado)
    ultima_fila = df_filt.sort_values("fecha").iloc[-1].copy()
    predicciones = []

    for i in range(horizonte):
        nueva_fecha = ultima_fila["fecha"] + timedelta(days=7 if unidad_tiempo == "semana" else 1)
        nueva_fila = ultima_fila.copy()
        nueva_fila["fecha"] = nueva_fecha

        # Actualizar variables temporales
        nueva_fila["mes"] = nueva_fecha.month
        nueva_fila["ano"] = nueva_fecha.year
        nueva_fila["dia_semana"] = nueva_fecha.weekday()
        nueva_fila["es_fin_de_semana"] = int(nueva_fila["dia_semana"] >= 5)

        # Features del modelo
        X = nueva_fila[["mes", "ano", "dia_semana", "es_fin_de_semana",
                        "lag_1", "lag_7", "lag_30", "rol_mean_7", "rol_std_30", "pct_change_7"]].values.reshape(1, -1)

        pred = modelo.predict(X)[0]

        nueva_fila["prediccion"] = pred
        predicciones.append(nueva_fila[["fecha", "producto_unidad", "region", "prediccion"]])

        # Actualizar para siguiente iteración
        ultima_fila["fecha"] = nueva_fecha
        ultima_fila["precio_normalizado"] = pred # Assuming normalized price is the prediction for next step
        ultima_fila["lag_1"] = pred
        # Need to update lag_7, lag_30, rol_mean_7, rol_std_30, pct_change_7 based on new prediction
        # This part of the original code's logic for updating lags and rolling features within the loop
        # seems simplified and might not accurately reflect how these features would evolve.
        # For a true time series prediction, you'd typically need more historical data or a more complex
        # way to simulate the future evolution of these features.
        # For now, keeping the original logic for demonstration, but be aware of this simplification.
        if len(predicciones) >= 7:
             ultima_fila["lag_7"] = predicciones[-7]["prediccion"]
        if len(predicciones) >= 30:
             ultima_fila["lag_30"] = predicciones[-30]["prediccion"]
        if len(predicciones) >= 7:
            ultima_fila["rol_mean_7"] = pd.DataFrame(predicciones[-7:])["prediccion"].mean()
        # Recalculating rolling std and pct_change accurately within this loop is complex
        # and might require more sophisticated simulation or external data.
        # Leaving them as simplified or static for now.
        ultima_fila["rol_std_30"] = 0 # Simplified
        ultima_fila["pct_change_7"] = 0 # Simplified


    df_pred = pd.DataFrame(predicciones)
    # Clean up filename
    cleaned_producto = producto.replace(" ", "_").replace("/", "_")
    cleaned_region = region.replace(" ", "_").replace("/", "_")
    cleaned_unidad_tiempo = unidad_tiempo.replace(" ", "_")
    salida_path = os.path.join(SALIDA_DIR, f"prediccion_{cleaned_producto}_{cleaned_region}_{cleaned_unidad_tiempo}.csv")

    df_pred.to_csv(salida_path, index=False)
    print(f"Predicción guardada en {salida_path}")
    return df_pred

# ==============================
# PIPELINE PRINCIPAL
# ==============================

def main():
    producto, unidad, region, horizonte, unidad_tiempo = parse_arguments()

    if not os.path.exists(DATOS_RECIENTES):
        print("No se encontró el archivo de datos recientes.")
        return

    df = pd.read_csv(DATOS_RECIENTES, parse_dates=["fecha"])


    pred = predecir_futuro(df, producto, unidad, region, horizonte, unidad_tiempo)
    if pred is not None:
        print(pred)

if __name__ == "__main__":
    main()