# Generated by Django 4.2.7 on 2025-11-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(db_index=True, max_length=100)),
                ('unidad_de_comercializacion', models.CharField(blank=True, max_length=80, null=True)),
                ('categoria_unidad', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('producto_unidad', models.CharField(db_index=True, max_length=150)),
                ('region', models.CharField(db_index=True, max_length=120)),
                ('mercado', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateField(db_index=True)),
                ('volumen', models.FloatField(blank=True, null=True)),
                ('precio_minimo', models.FloatField(blank=True, null=True)),
                ('precio_maximo', models.FloatField(blank=True, null=True)),
                ('precio_promedio', models.FloatField(blank=True, null=True)),
                ('precio_normalizado', models.FloatField(blank=True, db_index=True, null=True)),
                ('factor_inferido', models.FloatField(blank=True, null=True)),
                ('calidad', models.CharField(blank=True, max_length=80, null=True)),
                ('origen', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio Producto',
                'verbose_name_plural': 'Precios Productos',
                'indexes': [models.Index(fields=['producto_unidad', 'region', 'fecha'], name='prediccione_product_61dd49_idx'), models.Index(fields=['region', 'fecha'], name='prediccione_region_244355_idx'), models.Index(fields=['producto', 'fecha'], name='prediccione_product_414d4c_idx')],
                'unique_together': {('producto_unidad', 'region', 'fecha')},
            },
        ),
    ]
