# Generated by Django 4.2.7 on 2025-11-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='precioproducto',
            name='prediccione_product_61dd49_idx',
        ),
        migrations.RemoveIndex(
            model_name='precioproducto',
            name='prediccione_region_244355_idx',
        ),
        migrations.RemoveIndex(
            model_name='precioproducto',
            name='prediccione_product_414d4c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='precioproducto',
            unique_together={('producto_unidad', 'region', 'fecha', 'mercado', 'unidad_de_comercializacion', 'calidad')},
        ),
    ]
