# Generated by Django 5.2.8 on 2025-11-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaInteractivo', '0002_alter_region_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.AlterField(
            model_name='region',
            name='id_region',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='region',
            table=None,
        ),
    ]
