# Generated by Django 4.2.7 on 2025-10-24 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=255)),
                ('lineas_procesadas', models.IntegerField(default=0)),
                ('total_lineas', models.IntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_region', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaInteractivo.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subsector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaInteractivo.subsector'),
        ),
        migrations.CreateModel(
            name='DatosComercializacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('calidad', models.CharField(max_length=50)),
                ('unidad_comercializacion', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_maximo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_promedio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaInteractivo.mercado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaInteractivo.producto')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaInteractivo.region')),
                ('subsector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaInteractivo.subsector')),
                ('variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapaInteractivo.variedad')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha'], name='mapaInterac_fecha_862c95_idx'), models.Index(fields=['region'], name='mapaInterac_region__bf6352_idx'), models.Index(fields=['producto'], name='mapaInterac_product_45b80e_idx')],
            },
        ),
    ]
