# Generated by Django 5.2.8 on 2025-11-27 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapaInteractivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
    ]
