# Generated by Django 5.2.8 on 2025-11-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaInteractivo', '0003_remove_region_id_alter_region_id_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id_region',
            field=models.IntegerField(unique=True),
        ),
    ]
